"""mediciones creado_en

Revision ID: 265c15c78087
Revises: 3c683e68693b
Create Date: 2026-06-26 20:19:51.930626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265c15c78087'
down_revision: Union[str, Sequence[str], None] = '3c683e68693b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicion', sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### op.drop_column('medicion', 'creado_en')
    # ### end Alembic commands ###
