"""campo tabla mediciones

Revision ID: 3c683e68693b
Revises: b7d5a9adc842
Create Date: 2026-06-26 17:03:34.084659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c683e68693b'
down_revision: Union[str, Sequence[str], None] = 'b7d5a9adc842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicion', sa.Column('fecha_validacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicion', 'fecha_validacion')
    # ### end Alembic commands ###
