"""initial

Revision ID: 43ea612dee58
Revises: 
Create Date: 2026-06-24 19:16:03.846060

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ea612dee58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sampleTitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sampleDescription', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sampleSize', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sampleType', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sampleGeometry', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sampleTakenOn', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('acquisitionStarted', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('texto_markdown', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicion_id', sa.Integer(), nullable=False),
    sa.Column('nuclideName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('IdConfidence', sa.Float(), nullable=False),
    sa.Column('Activity', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ActivityUncertainty', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['medicion_id'], ['medicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable')
    op.drop_table('medicion')
    # ### end Alembic commands ###
