"""mediciones fecha_aprobacion

Revision ID: 50711c11f925
Revises: 9e219979c5cc
Create Date: 2026-06-27 12:30:35.782158

"""
from typing import Sequence, Union

from alembic import op # pyright: ignore[reportUnusedImport] #  # noqa: F401
import sqlalchemy as sa  # pyright: ignore[reportUnusedImport] # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '50711c11f925'
down_revision: Union[str, Sequence[str], None] = '9e219979c5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   #  op.add_column('medicion', sa.Column('creado_en', sa.DateTime(), nullable=True))
    # op.add_column('medicion', sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True))
    # op.drop_constraint(None, 'variable', type_='foreignkey')
    # op.create_foreign_key(None, 'variable', 'medicion', ['medicion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'variable', type_='foreignkey')
    # op.create_foreign_key(None, 'variable', 'medicion', ['medicion_id'], ['id'])
    # op.drop_column('medicion', 'fecha_aprobacion')
    # op.drop_column('medicion', 'creado_en')
    # ### end Alembic commands ###
