"""mediciones variabels on delete cascade

Revision ID: 9e219979c5cc
Revises: 265c15c78087
Create Date: 2026-06-26 22:09:11.045005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e219979c5cc'
down_revision: Union[str, Sequence[str], None] = '265c15c78087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicion', 'creado_en')
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.create_foreign_key(None, 'variable', 'medicion', ['medicion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variable', type_='foreignkey')
    op.create_foreign_key(None, 'variable', 'medicion', ['medicion_id'], ['id'])
    op.add_column('medicion', sa.Column('creado_en', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
