"""tabla usuarios

Revision ID: b3831a6b8c2f
Revises: 43ea612dee58
Create Date: 2026-06-24 19:24:55.101700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'b3831a6b8c2f'
down_revision: Union[str, Sequence[str], None] = '43ea612dee58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicion')
    op.drop_table('variable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('medicion_id', sa.INTEGER(), nullable=False),
    sa.Column('nuclideName', sa.VARCHAR(length=50), nullable=False),
    sa.Column('IdConfidence', sa.FLOAT(), nullable=False),
    sa.Column('Activity', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ActivityUncertainty', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['medicion_id'], ['medicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sampleTitle', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sampleDescription', sa.VARCHAR(), nullable=False),
    sa.Column('sampleSize', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sampleType', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sampleGeometry', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sampleTakenOn', sa.VARCHAR(length=100), nullable=False),
    sa.Column('acquisitionStarted', sa.VARCHAR(length=100), nullable=False),
    sa.Column('texto_markdown', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
