"""tabla usuarios2

Revision ID: b7d5a9adc842
Revises: b3831a6b8c2f
Create Date: 2026-06-24 19:26:56.444818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = 'b7d5a9adc842'
down_revision: Union[str, Sequence[str], None] = 'b3831a6b8c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sampleTitle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sampleDescription', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sampleSize', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sampleType', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sampleGeometry', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('sampleTakenOn', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('acquisitionStarted', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('texto_markdown', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('image_file', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicion_id', sa.Integer(), nullable=False),
    sa.Column('nuclideName', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('IdConfidence', sa.Float(), nullable=False),
    sa.Column('Activity', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ActivityUncertainty', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['medicion_id'], ['medicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('medicion')
    # ### end Alembic commands ###
